### ISSUE TITLE
Not enough GC roots created to prevent nix gc from removing stuff

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_nixpkgs#105]
after a `nix-store --gc`:

```
INFO: Call stack for the definition of repository 'stackage' which is a _stack_snapshot (rule definition at /home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell/haskell/cabal.bzl:970:19):
 - /home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell/haskell/cabal.bzl:1184:5
 - /home/philip/kot/work/tweag/someproject/WORKSPACE:128:1
ERROR: An error occurred during the fetch of repository 'stackage':
   Traceback (most recent call last):
	File "/home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell/haskell/cabal.bzl", line 865
		_compute_dependency_graph(<6 more arguments>)
	File "/home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell/haskell/cabal.bzl", line 713, in _compute_dependency_graph
		repository_ctx.path(<1 more arguments>)
Not a regular file: /home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell_stack/stack
ERROR: /home/philip/kot/work/tweag/someproject/backend/tests/api-tests/BUILD.bazel:7:1: //backend/tests/api-tests:api-tests depends on @stackage//:base in repository @stackage which failed to fetch. no such package '@stackage//': Traceback (most recent call last):
	File "/home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell/haskell/cabal.bzl", line 865
		_compute_dependency_graph(<6 more arguments>)
	File "/home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell/haskell/cabal.bzl", line 713, in _compute_dependency_graph
		repository_ctx.path(<1 more arguments>)
Not a regular file: /home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell_stack/stack
ERROR: /home/philip/kot/work/tweag/someproject/backend/tests/api-tests/BUILD.bazel:7:1: //backend/tests/api-tests:api-tests depends on @stackage//:bytestring in repository @stackage which failed to fetch. no such package '@stackage//': Traceback (most recent call last):
	File "/home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell/haskell/cabal.bzl", line 865
		_compute_dependency_graph(<6 more arguments>)
	File "/home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell/haskell/cabal.bzl", line 713, in _compute_dependency_graph
		repository_ctx.path(<1 more arguments>)
Not a regular file: /home/philip/.cache/bazel/_bazel_philip/ec4bffc753a4896ad5f0595f4cbba0c3/external/rules_haskell_stack/stack

and so on
```

We must be missing some GC roots.

```
> bazel version
Another command (pid=3664) is running.  Waiting for it to complete on the server...
Build label: 2.0.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

```
http_archive(
    name = "rules_haskell",
    strip_prefix = "rules_haskell-1150e2158fc21a365920a4a42a3aa6f79cdf49c3",
    # rules_haskell master 2020-01-30
    urls = ["https://github.com/tweag/rules_haskell/archive/1150e2158fc21a365920a4a42a3aa6f79cdf49c3.tar.gz"],
    sha256 = "1bbd30c24434a7272da77c664bd4b01083cd412cd0b6ad511ed9247bb6d2f55a",
)
```

which according to 
https://github.com/tweag/rules_haskell/blob/1150e2158fc21a365920a4a42a3aa6f79cdf49c3/haskell/repositories.bzl#L51-L57
is rules_nixpkgs 0.6.0

TODO: create repro

**Comment by aherrmann** [comment]
We haven't seen any other reports of this issue, and no repro is available to date. I'm closing, but please re-open and comment if you encounter this issue.
