### ISSUE TITLE
Checksum for v0.8.0.tar.gz release has changed?

### ISSUE THREAD

**Issue by jonathanlking** [tweag/rules_nixpkgs#310]
**Describe the bug**

It _appears_ that the checksum for [Release 0.8.0](https://github.com/tweag/rules_nixpkgs/releases/tag/v0.8.0) has changed from `7aee35c95251c1751e765f7da09c3bb096d41e6d6dca3c72544781a5573be4aa` (included in the release notes) to `cac383e48d95c06f2de64912a90c596eb76944d05be0148124d0eb07f949b45f` (reported by Bazel as the actual).

This behaviour was first spotted at around 18:30 UTC today.

**To Reproduce**

Have a Bazel project that loads in `v0.8.0` (e.g. https://github.com/jonathanlking/minirepo/tree/ghc-8.8).
Then completely clean the bazel cache/invalidate the existing copy by changing the `sha256` to a dummy value.

```
Starting local Bazel server and connecting to it...
INFO: Repository io_tweag_rules_nixpkgs instantiated at:
  /home/jonathan/github/minirepo/WORKSPACE:25:23: in <toplevel>
  /home/jonathan/github/minirepo/bazel/repository/dependencies.bzl:20:17: in workspace_dependencies
Repository rule http_archive defined at:
  /home/jonathan/.cache/bazel/_bazel_jonathan/66458c4d0c143c7c3013155003bec59d/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/tweag/rules_nixpkgs/archive/v0.8.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was cac383e48d95c06f2de64912a90c596eb76944d05be0148124d0eb07f949b45f but wanted 7aee35c95251c1751e765f7da09c3bb096d41e6d6dca3c72544781a5573be4aa
ERROR: An error occurred during the fetch of repository 'io_tweag_rules_nixpkgs':
   Traceback (most recent call last):
        File "/home/jonathan/.cache/bazel/_bazel_jonathan/66458c4d0c143c7c3013155003bec59d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/tweag/rules_nixpkgs/archive/v0.8.0.tar.gz] to /home/jonathan/.cache/bazel/_bazel_jonathan/66458c4d0c143c7c3013155003bec59d/external/io_tweag_rules_nixpkgs/temp6812389466972650811/v0.8.0.tar.gz: Checksum was cac383e48d95c06f2de64912a90c596eb76944d05be0148124d0eb07f949b45f but wanted 7aee35c95251c1751e765f7da09c3bb096d41e6d6dca3c72544781a5573be4aa
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/home/jonathan/.cache/bazel/_bazel_jonathan/66458c4d0c143c7c3013155003bec59d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/tweag/rules_nixpkgs/archive/v0.8.0.tar.gz] to /home/jonathan/.cache/bazel/_bazel_jonathan/66458c4d0c143c7c3013155003bec59d/external/io_tweag_rules_nixpkgs/temp6812389466972650811/v0.8.0.tar.gz: Checksum was cac383e48d95c06f2de64912a90c596eb76944d05be0148124d0eb07f949b45f but wanted 7aee35c95251c1751e765f7da09c3bb096d41e6d6dca3c72544781a5573be4aa
ERROR: no such package '@io_tweag_rules_nixpkgs//nixpkgs': java.io.IOException: Error downloading [https://github.com/tweag/rules_nixpkgs/archive/v0.8.0.tar.gz] to /home/jonathan/.cache/bazel/_bazel_jonathan/66458c4d0c143c7c3013155003bec59d/external/io_tweag_rules_nixpkgs/temp6812389466972650811/v0.8.0.tar.gz: Checksum was cac383e48d95c06f2de64912a90c596eb76944d05be0148124d0eb07f949b45f but wanted 7aee35c95251c1751e765f7da09c3bb096d41e6d6dca3c72544781a5573be4aa
```

**Expected behavior**

`rules_nixpkgs` to be loaded (i.e. to have the `7aee35c95251c1751e765f7da09c3bb096d41e6d6dca3c72544781a5573be4aa` checksum).

**Environment**
 - OS name + version: Ubuntu 22.04 (Bazel 4.2.2)
 - Version of the code: 0.8.0

**Additional context**

It is possible this is user error on my part, I'm terribly sorry if so!
I've reproduced this across multiple machines (including on CI agents which are ephemeral) and across different projects (including the open sourced one linked), which has given me the confidence to report this as a bug. I'm very confused about what could have caused this though 🤔

**Comment by airportyh** [comment]
I ran into the same issue. Verified with sha256sum:

```
$ wget https://github.com/tweag/rules_nixpkgs/archive/v0.8.0.tar.gz
$ sha256sum v0.8.0.tar.gz 
cac383e48d95c06f2de64912a90c596eb76944d05be0148124d0eb07f949b45f  v0.8.0.tar.gz
```

**Comment by jonathanlking** [comment]
I ran a diff against a cached earlier version still on my machine; I believe the only change is to the WORKSPACE file:

```
diff --color -bur rules_nixpkgs-0.8.0/WORKSPACE /home/jonathan/.cache/bazel/_bazel_jonathan/66458c4d0c143c7c3013155003bec59d/external/io_tweag_rules_nixpkgs/WORKSPACE
--- rules_nixpkgs-0.8.0/WORKSPACE	2021-02-11 13:51:44.000000000 +0000
+++ /home/jonathan/.cache/bazel/_bazel_jonathan/66458c4d0c143c7c3013155003bec59d/external/io_tweag_rules_nixpkgs/WORKSPACE	2023-01-30 20:35:08.880834882 +0000
@@ -1,260 +1 @@
 workspace(name = "io_tweag_rules_nixpkgs")
-
-load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
-load("//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
-
-rules_nixpkgs_dependencies()
-
-load(
-    "//nixpkgs:nixpkgs.bzl",
-    "nixpkgs_cc_configure",
-    "nixpkgs_git_repository",
-    "nixpkgs_local_repository",
-    "nixpkgs_package",
-    "nixpkgs_python_configure",
-    "nixpkgs_sh_posix_configure",
-)
-
-# For documentation
-
-http_archive(
-    name = "io_bazel_stardoc",
-    sha256 = "6d07d18c15abb0f6d393adbd6075cd661a2219faab56a9517741f0fc755f6f3c",
-    strip_prefix = "stardoc-0.4.0",
-    urls = [
-        "https://mirror.bazel.build/github.com/bazelbuild/stardoc/archive/0.4.0.tar.gz",
-        "https://github.com/bazelbuild/stardoc/archive/0.4.0.tar.gz",
-    ],
-)
-
-load("@io_bazel_stardoc//:setup.bzl", "stardoc_repositories")
-
-stardoc_repositories()
-
-# For tests
-
-load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
-
-bazel_skylib_workspace()
-
-nixpkgs_git_repository(
-    name = "remote_nixpkgs",
-    remote = "https://github.com/NixOS/nixpkgs",
-    revision = "18.09",
-    sha256 = "6451af4083485e13daa427f745cbf859bc23cb8b70454c017887c006a13bd65e",
-)
-
-nixpkgs_local_repository(
-    name = "nixpkgs",
-    nix_file = "//:nixpkgs.nix",
-    nix_file_deps = ["//:nixpkgs.json"],
-)
-
-# This is the commit introducing a Nix version working in the Bazel
-# sandbox
-nixpkgs_git_repository(
-    name = "remote_nixpkgs_for_nix_unstable",
-    remote = "https://github.com/NixOS/nixpkgs",
-    revision = "15d1011615d16a8b731adf28e2cfc33481102780",
-    sha256 = "8b1161a249d50effea1f240c34a81832a88c8d5d274314ae6225fd78bd62dfb9",
-)
-
-nixpkgs_package(
-    name = "nix-unstable",
-    attribute_path = "nixUnstable",
-    repositories = {"nixpkgs": "@remote_nixpkgs_for_nix_unstable"},
-)
-
-nixpkgs_package(
-    name = "nixpkgs-git-repository-test",
-    attribute_path = "hello",
-    repositories = {"nixpkgs": "@remote_nixpkgs"},
-)
-
-nixpkgs_package(
-    name = "hello",
-    # Deliberately not repository, to test whether repositories works.
-    repositories = {"nixpkgs": "@nixpkgs"},
-)
-
-nixpkgs_package(
-    name = "expr-test",
-    nix_file_content = "let pkgs = import <nixpkgs> { config = {}; overlays = []; }; in pkgs.hello",
-    nix_file_deps = ["//:nixpkgs.json"],
-    # Deliberately not @nixpkgs, to test whether explict file works.
-    repositories = {"nixpkgs": "//:nixpkgs.nix"},
-)
-
-nixpkgs_package(
-    name = "attribute-test",
-    attribute_path = "hello",
-    repository = "@nixpkgs",
-)
-
-nixpkgs_package(
-    name = "expr-attribute-test",
-    attribute_path = "hello",
-    nix_file_content = "import <nixpkgs> { config = {}; overlays = []; }",
-    repository = "@nixpkgs",
-)
-
-nixpkgs_package(
-    name = "nix-file-test",
-    attribute_path = "hello",
-    nix_file = "//tests:nixpkgs.nix",
-    repository = "@nixpkgs",
-)
-
-nixpkgs_package(
-    name = "nix-file-deps-test",
-    nix_file = "//tests:hello.nix",
-    nix_file_deps = ["//tests:pkgname.nix"],
-    repository = "@nixpkgs",
-)
-
-nixpkgs_package(
-    name = "output-filegroup-test",
-    nix_file = "//tests:output.nix",
-    repository = "@nixpkgs",
-)
-
-nixpkgs_package(
-    name = "extra-args-test",
-    nix_file_content = """
-{ packagePath }: (import <nixpkgs> { config = {}; overlays = []; }).${packagePath}
-    """,
-    nixopts = [
-        "--argstr",
-        "packagePath",
-        "hello",
-    ],
-    repository = "@nixpkgs",
-)
-
-nixpkgs_package(
-    name = "output-filegroup-manual-test",
-    build_file_content = """
-package(default_visibility = [ "//visibility:public" ])
-filegroup(
-    name = "manual-filegroup",
-    srcs = glob(["hi-i-exist", "hi-i-exist-too", "bin/*"]),
-)
-""",
-    nix_file = "//tests:output.nix",
-    repository = "@nixpkgs",
-)
-
-nixpkgs_package(
-    name = "relative-imports",
-    attribute_path = "hello",
-    nix_file = "//tests:relative_imports.nix",
-    nix_file_deps = [
-        "//:nixpkgs.json",
-        "//:nixpkgs.nix",
-        "//tests:relative_imports/nixpkgs.nix",
-    ],
-    repository = "@nixpkgs",
-)
-
-# This bazel build @output-derivation-is-a-file//... must fail
-# See https://github.com/tweag/rules_nixpkgs/issues/99 for details
-nixpkgs_package(
-    name = "output-derivation-is-a-file",
-    attribute_path = "",
-    nix_file_content = """let pkgs = import <nixpkgs> { config = {}; overlays = []; }; in pkgs.writeText "foo" "bar" """,
-    nix_file_deps = [
-        "//:nixpkgs.json",
-        "//:nixpkgs.nix",
-        "//tests:relative_imports/nixpkgs.nix",
-    ],
-    repository = "@nixpkgs",
-)
-
-# This is used to run Nix in a sandboxed Bazel test. See the test
-# run-test-invalid-nixpkgs-package.
-nixpkgs_package(
-    name = "busybox_static",
-    attribute_path = "pkgsStatic.busybox",
-    repository = "@nixpkgs",
-)
-
-nixpkgs_cc_configure(
-    # Use a different name to be able to distinguish this toolchain from the
-    # builtin one in the tests.
-    name = "nixpkgs_config_cc",
-    repository = "@remote_nixpkgs",
-)
-
-nixpkgs_python_configure(
-    python2_attribute_path = "python2",
-    repository = "@remote_nixpkgs",
-)
-
-nixpkgs_package(
-    name = "nixpkgs_python_configure_test",
-    nix_file = "//tests:python-test.nix",
-    repository = "@remote_nixpkgs",
-)
-
-local_repository(
-    name = "nixpkgs_location_expansion_test_file",
-    path = "tests/location_expansion/test_repo",
-)
-
-nixpkgs_package(
-    name = "nixpkgs_location_expansion_test",
-    build_file_content = "exports_files(glob(['out/**']))",
-    nix_file = "//tests:location_expansion.nix",
-    nix_file_deps = [
-        "//tests:location_expansion/test_file",
-        "@nixpkgs_location_expansion_test_file//:test_file",
-    ],
-    nixopts = [
-        "--arg",
-        "local_file",
-        "$(location //tests:location_expansion/test_file)",
-        "--arg",
-        "external_file",
-        "$(location @nixpkgs_location_expansion_test_file//:test_file)",
-    ],
-    repository = "@remote_nixpkgs",
-)
-
-http_archive(
-    name = "rules_sh",
-    sha256 = "83a065ba6469135a35786eb741e17d50f360ca92ab2897857475ab17c0d29931",
-    strip_prefix = "rules_sh-0.2.0",
-    urls = ["https://github.com/tweag/rules_sh/archive/v0.2.0.tar.gz"],
-)
-
-load("@rules_sh//sh:repositories.bzl", "rules_sh_dependencies")
-
-rules_sh_dependencies()
-
-nixpkgs_sh_posix_configure(repository = "@nixpkgs")
-
-load("@rules_sh//sh:posix.bzl", "sh_posix_configure")
-
-sh_posix_configure()
-
-# go toolchain test
-
-http_archive(
-    name = "io_bazel_rules_go",
-    sha256 = "7904dbecbaffd068651916dce77ff3437679f9d20e1a7956bff43826e7645fcc",
-    urls = [
-        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.25.1/rules_go-v0.25.1.tar.gz",
-        "https://github.com/bazelbuild/rules_go/releases/download/v0.25.1/rules_go-v0.25.1.tar.gz",
-    ],
-)
-
-load(
-    "//nixpkgs:toolchains/go.bzl",
-    "nixpkgs_go_configure",
-)
-
-nixpkgs_go_configure(repository = "@nixpkgs")
-
-load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
-
-go_rules_dependencies()
```

**Comment by jonathanlking** [comment]
It appears the checksums have also changed for

* [rules_haskell Release 0.15](https://github.com/tweag/rules_haskell/releases/tag/v0.15)

```
$ wget https://github.com/tweag/rules_haskell/archive/v0.15.tar.gz
$ sha256sum v0.15.tar.gz
ca268fb43ff1b7751db0b8ac425a2b472cc86c9ad2f1e8d1ea82457615644617  v0.15.tar.gz
```

* [rules_sh Release 0.2.0](https://github.com/tweag/rules_sh/releases/tag/v0.2.0)

```
$ wget https://github.com/tweag/rules_sh/archive/v0.2.0.tar.gz
$ sha256sum v0.2.0.tar.gz
d9d947448c456114ed9b0ae4964f2299dbe8343f29a29b47ed3900b3b3a7e903  v0.2.0.tar.gz
```

**Comment by jonathanlking** [comment]
A stab in the dark here, but perhaps the `WORKSPACE` files aren't meant to be included in the releases? (I spotted the same diff with `rules_haskell`).
This would differ from the contents of the git repo at that commit though (e.g. https://github.com/tweag/rules_nixpkgs/blob/6178f2aae7a90370f2132abafa977701afc6fb4e/WORKSPACE for v0.8.0).
I'm not familiar with how the `.tar.gz` is created, but maybe this process has been run again today? (either by you or by GitHub?).

**Comment by airportyh** [comment]
I got a mismatch for the package https://github.com/bazelbuild/rules_python/archive/refs/tags/0.8.0.tar.gz  as well, and that's from a different author...

**Comment by airportyh** [comment]
Appears to be a github bug: https://github.com/orgs/community/discussions/45830

**Comment by jonathanlking** [comment]
From a quick search on Twitter it looks like it's a GitHub issue 😔 
https://twitter.com/kgreenek/status/1620164769931202560
https://twitter.com/thesayynn/status/1620129657977987073

**Comment by jonathanlking** [comment]
This is now fixed 😌

**Comment by avdv** [comment]
Thanks for the report, it's interesting how many people relied on this behavior. We've also seen something like this in rules_haskell a few weeks ago which is probably what happened at Github in a much larger scale now: https://github.com/tweag/rules_haskell/pull/1847

We need to see whether we can still rely on the current mechanism for the future, or if we need to create artifacts for each release to be on the safe side.

**Comment by aherrmann** [comment]
For reference, here's the related discussion in the Bazel rule author SIG: https://github.com/bazel-contrib/SIG-rules-authors/issues/11

**Comment by avdv** [comment]
But also, it seems like we use the unstable URL instead of the stable one:

> I checked with our team and they confirmed that we can expect the checksums for repository release archives, found at /archive/refs/tags/$tag, to be stable going forward. That cannot be said, however, for repository code download archives found at archive/v6.0.4.

`https://github.com/tweag/rules_nixpkgs/archive/v0.8.0.tar.gz` vs.
`https://github.com/tweag/rules_nixpkgs/archive/refs/tags/v0.8.0.tar.gz`

**Comment by aherrmann** [comment]
> But also, it seems like we use the unstable URL instead of the stable one:

Good catch! I've verified that (after GH's roll-back) the artifacts from the `refs/tags` URL have the same sha256 and updated the setup instructions on the 0.8.0 and 0.9.0 releases to use these URLs.
